version: "3.9"

services:
  backend:
    build:
      context: ./src
    container_name: intro-backend
    ports:
      - "4000:4000"
    networks:
      - intro-net

  frontend:
    build:
      context: ./frontend
    container_name: intro-frontend
    ports:
      - "3000:80"
    networks:
      - intro-net

networks:
  intro-net:
    driver: bridge